# Generated by Django 3.1 on 2020-12-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_super_qualifier', models.BooleanField(default=False)),
                ('group', models.CharField(default='Unknown', max_length=10)),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'club',
            },
        ),
    ]
